[package]
name = "redirectionio"
description = "Redirection IO Library to handle matching rule, redirect and filtering headers and body."
repository = "https://github.com/redirectionio/libredirectionio"
license = "MIT"
version = "0.1.0"
authors = ["Joel Wurtz <jwurtz@jolicode.com>"]
edition = "2018"
build = "src/build.rs"

[features]
default = ["console_error_panic_hook"]

[lib]
name = "redirectionio"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
cbindgen="0.17.0"
libtool = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.16"
tera = "1.6.1"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.61"
regex = "1.4.3"
url = "2.2.0"
percent-encoding = "2.1.0"
lazy_static = "1.4.0"
wasm-bindgen = "0.2.70"
console_error_panic_hook = { version = "0.1.1", optional = true }
wee_alloc = { version = "0.4.2", optional = true }
cfg-if = "1.0.0"
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
libc = "0.2.84"
heck = "0.3.2"
log = "0.4.14"
stderrlog = "0.5.1"
console_log = "0.2.0"
scraper = "0.12.0"
http = "0.2.3"
string_cache = "0.8.1"

[dev-dependencies]
criterion = "0.3.4"

[[bench]]
name = "match_rule_benchmark"
harness = false

[[bench]]
name = "build_router_rule_benchmark"
harness = false

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]

[profile.release]
opt-level = "s"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
