[package]
name = "redirectionio"
description = "Redirection IO Library to handle matching rule, redirect and filtering headers and body."
repository = "https://github.com/redirectionio/libredirectionio"
license = "MIT"
version = "0.1.0"
authors = ["Joel Wurtz <jwurtz@jolicode.com>"]
edition = "2018"
build = "src/build.rs"

[lib]
name = "redirectionio"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
cbindgen="0.20.0"
libtool = "0.1.1"
linked_hash_set = { version = "0.1.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.21"
tera = "1.15.0"

[dependencies]
cfg-if = "1.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
cidr = { version = "0.2.1", features = ["serde"] }
console_log = "0.2.0"
heck = "0.3.3"
http = "0.2.5"
lazy_static = "1.4.0"
libc = "0.2.107"
log = "0.4.14"
percent-encoding = "2.1.0"
regex = "1.5.4"
scraper = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.70"
stderrlog = "0.5.1"
string_cache = "=0.8.1"
url = "2.2.2"
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen = "0.2.78"

[dev-dependencies]
criterion = "0.3.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wee_alloc = { version = "0.4.5" }
console_error_panic_hook = { version = "0.1.7" }

[[bench]]
name = "match_rule_benchmark"
harness = false

[[bench]]
name = "build_router_rule_benchmark"
harness = false

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
