[package]
name = "redirectionio"
description = "Redirection IO Library to handle matching rule, redirect and filtering headers and body."
repository = "https://github.com/redirectionio/libredirectionio"
license = "MIT"
version = "0.1.0"
authors = ["Joel Wurtz <jwurtz@jolicode.com>"]
edition = "2018"
build = "src/build.rs"

[features]
default = ["console_error_panic_hook"]

[lib]
name = "redirectionio"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
cbindgen="0.9.1"
libtool = "0.1.1"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.3.1"
url = "1"
lazy_static = "1.2.0"
wasm-bindgen = "0.2.51"
console_error_panic_hook = { version = "0.1.1", optional = true }
wee_alloc = { version = "0.4.2", optional = true }
cfg-if = "0.1"
uuid = { version = "0.7", features = ["serde", "v4", "wasm-bindgen"] }
libc = "0.2.53"
heck = "0.3.1"
log = "0.4.6"
stderrlog = "0.4.1"
console_log = "0.1.2"
scraper = "0.10.1"
http = "0.2.1"
string_cache = "0.8.0"

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "match_rule_benchmark"
harness = false

[[bench]]
name = "build_router_rule_benchmark"
harness = false

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]

[profile.release]
opt-level = "s"

[[test]]
name = "small-stack"
harness = false

[[test]]
name = "playground"
harness = false
