name: Release beta release

on:
    release:
        types: [prereleased]

jobs:
    trigger-circleci:
        runs-on: ubuntu-latest
        steps:
            - run: echo $REF
              env:
                  ref: ${{ github.ref }}
