name: Release test release

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    trigger-circleci:
        runs-on: ubuntu-latest
        steps:
            -
                name: Set major version
                run: MAJOR_VERSION=`sed -E 's/[^0-9]+?([0-9]+)\.([0-9]+)\.([0-9]+).+?/\1/' <<< $VERSION` echo "::set-env name=action_state::$MAJOR_VERSION"
                env:
                    VERSION: v1.0.0

            -
                name: Debug
                run: echo "$MAJOR_VERSION $VERSION"
                env:
                    VERSION: v1.0.0
