name: Test env

on: [push, pull_request]

jobs:
    trigger-circleci:
        runs-on: ubuntu-latest
        steps:
            -
                name: Set version
                env:
                    REF: 'v1.2.3'
                run: VERSION=`sed -E 's/[^0-9]+?([0-9]+\.[0-9]+\.[0-9]+.+?)/\1/' <<< $REF` && echo "VERSION=$VERSION" >> $GITHUB_ENV

            -
                name: Set major version
                run: MAJOR_VERSION=`sed -E 's/[^0-9]+?([0-9]+)\.([0-9]+)\.([0-9]+).+?/\1/' <<< $VERSION` && echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV

            -
                name: Trigger Circle CI API
                env:
                    CIRCLE_API_TOKEN: ${{ secrets.CIRCLE_API_TOKEN }}
                run: echo $VERSION && echo " yolo " && echo $MAJOR_VERSION
