name: Release test release

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    trigger-circleci:
        runs-on: ubuntu-latest
        steps:
            - run: echo $REF
              env:
                  ref: ${{ github.ref }}
